import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-[#0e0c15] text-white">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen relative overflow-hidden`}
      >
        {/* Background Blur + Gradient */}
        <div className="absolute inset-0 -z-10">
          <div className="w-full h-full bg-gradient-to-b from-[#100e1a] via-[#1c122e] to-[#0e0c15] blur-2xl opacity-80"></div>
        </div>

        {children}
      </body>
    </html>
  );
}
